### ISSUE TITLE
Interesting, I am using the same approach but still duplicated records

### ISSUE THREAD

**Issue by chaoyangnz** [AnghelLeonard/Hibernate-SpringBoot#2]
I am using `findAll(Specification, Pageable)` with hints, but the result still contains duplicated records.

Hibernate 5.3.x
Postgres 9.6

**Comment by AnghelLeonard** [comment]
Can you please provide your query?
Notice that, `hibernate.query.passDistinctThrough` doesn't work for scalar queries. In such cases, DISTINCT must be passed to the database.

**Comment by AnghelLeonard** [comment]
Also, if `hibernate.use_sql_comments` is enabled the `hibernate.query.passDistinctThrough` doesn't work.

**Comment by chaoyangnz** [comment]
I set `spring.jpa.properties.hibernate.use_sql_comments=false`

this is the SQL logs:
```
Hibernate: 
    select
        storyentit0_.id as id1_1_0_,
        externalas6_.asset_id as asset_id3_10_1_,
        assetsubty7_.name as name1_7_2_,
        storyentit0_1_.asset_sub_type_name as asset_su7_1_0_,
        storyentit0_1_.created_by as created_2_1_0_,
        storyentit0_1_.created_date as created_3_1_0_,
        storyentit0_1_.last_updated as last_upd4_1_0_,
        storyentit0_1_.locked_by as locked_b5_1_0_,
        storyentit0_1_.headline as headline6_1_0_,
        storyentit0_.print_slug as print_sl1_18_0_,
        storyentit0_.text_searchable as text_sea2_18_0_,
        storyentit0_.thumbnail_image_id as thumbnai4_18_0_,
        externalas6_.asset_cms_id as asset_cm1_10_1_,
        externalas6_.asset_cms_source as asset_cm2_10_1_,
        assetsubty7_.display_name as display_2_7_2_,
        assetsubty7_.asset_type_id as asset_ty3_7_2_ 
    from
        story storyentit0_ 
    inner join
        asset storyentit0_1_ 
            on storyentit0_.id=storyentit0_1_.id 
    left outer join
        independent_asset_properties independen1_ 
            on storyentit0_.id=independen1_.asset_id 
    left outer join
        asset_flags flags2_ 
            on independen1_.asset_id=flags2_.asset_entity_id 
    left outer join
        flag flagentity3_ 
            on flags2_.flags_name=flagentity3_.name 
    left outer join
        asset_ad_exclusions adexclusio4_ 
            on independen1_.asset_id=adexclusio4_.asset_entity_id 
    left outer join
        ad_exclusion adexclusio5_ 
            on adexclusio4_.ad_exclusions_name=adexclusio5_.name 
    left outer join
        external_asset_properties externalas6_ 
            on storyentit0_.id=externalas6_.asset_id 
    left outer join
        asset_sub_type assetsubty7_ 
            on storyentit0_1_.asset_sub_type_name=assetsubty7_.name 
    where
        flagentity3_.name=? 
        or adexclusio5_.name=? limit ?
TRACE 2019/10/19 17:54:02,727 [main] (o.h.t.d.s.BasicBinder.bind:65) - binding parameter [1] as [VARCHAR] - [HOT]
TRACE 2019/10/19 17:54:02,727 [main] (o.h.t.d.s.BasicBinder.bind:65) - binding parameter [2] as [VARCHAR] - [TRAVEL_INCIDENT]
TRACE 2019/10/19 17:54:02,740 [main] (o.s.t.i.TransactionInterceptor.commitTransactionAfterReturning:531) - Completing transaction for [org.springframework.data.jpa.repository.support.SimpleJpaRepository.findAll]
```

In code, I set:

```
query.distinct(true);
```

and add @QueryHints:

```
@EntityGraph(attributePaths = {"assetSubTypeEntity", "externalAssetProperties"})
    @QueryHints(value = {
            @QueryHint(name = org.hibernate.jpa.QueryHints.HINT_PASS_DISTINCT_THROUGH, value = "false"),
            @QueryHint(name = org.hibernate.jpa.QueryHints.HINT_READONLY, value = "true")
        }, forCounting = false)
    @Override
    Page<StoryEntity> findAll(Specification<StoryEntity> spec, Pageable pageable);
```

**Comment by AnghelLeonard** [comment]
Just for the record, if you remove the `HINT_PASS_DISTINCT_THROUGH` then `DISTINCT` appears in the generated SQL and you obtain no duplicates?

**Comment by chaoyangnz** [comment]
yes, remove `HINT_PASS_DISTINCT_THROUGH` hint, then the generated SQL has `distinct` and no duplicates.

**Comment by AnghelLeonard** [comment]
I see that your entities are suffixed with `Entity`, while `externalAssetProperties` is not suffixed this way. Anyway, please send me an e-mail (leoprivacy@yahoo.com) with only the involved classes (involved entities, the specification, and the repository).

**Comment by chaoyangnz** [comment]
thanks, will do tomorrow. 

I tried to debug to Hibernate source code. I even searched all the logic around the hint and found Hibernate just set the hint but nowhere to use the hint. Could you tell me where is the logic in Hibernate source code it deduplicates in application rather than in database. I doubt Hibernate just remove distinct keyword from HQL but do nothing.

**Comment by AnghelLeonard** [comment]
I will search in the code and let you know. Meanwhile, until you can make your code available, consider reading this article: https://planet.jboss.org/post/the_distinct_pass_through_hibernate_query_hint. Explains the logic behind this hint. 

In a nutshell, DISTINCT in JPQL (HQL) is used by JPA to avoid returning the same parent entities when JOIN FETCH-ing parents with child associations. So, it operates at the application-level. Passing DISTINCT to the database adds an overhead especially if the JDBC result set has no duplicates since it will have a negative impact on Execution Plan.

**Comment by AnghelLeonard** [comment]
I am not 100% sure but I found this:

In `org.hibernate.loader.hql.QueryLoader`, the `getResultList()` uses a `ResultTransformer.trasnformList()` method:

`return resultTransformer.transformList( results );`

One of the transformers is `DistinctResultTransformer` which eliminates duplicates as follows:

`@Override`
`public List transformList(List list) {`
&nbsp;&nbsp;&nbsp;&nbsp;`List<Object> result = new ArrayList<Object>( list.size() );`
&nbsp;&nbsp;&nbsp;&nbsp;`Set<Identity> distinct = new HashSet<Identity>();`
&nbsp;&nbsp;&nbsp;&nbsp;`for ( Object entity : list ) {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`if ( distinct.add( new Identity( entity ) ) ) {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`result.add( entity );`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`}`
&nbsp;&nbsp;&nbsp;&nbsp;`}`
&nbsp;&nbsp;&nbsp;&nbsp;`LOG.debugf( "Transformed: %s rows to: %s distinct results", list.size(), result.size() );`
&nbsp;&nbsp;&nbsp;&nbsp;`return result;`
`}`

**Comment by chaoyangnz** [comment]
right, that transformer seems the correct place. but it is deprecated since Hibernate 5.2, see [this](https://discourse.hibernate.org/t/hibernate-resulttransformer-is-deprecated-what-to-use-instead/232). And in `QueryImpl`, the transformers are null.
So the logic is never applied.

**Comment by chaoyangnz** [comment]
see this original Pull request: https://github.com/hibernate/hibernate-orm/commit/1661af2d8f4ae109625a141abc19599d9a919f01 

@vladmihalcea

**Comment by AnghelLeonard** [comment]
Yes, that is how the hint suppresses `DISTINCT` to go to the database.

**Comment by chaoyangnz** [comment]
found the cause: https://github.com/hibernate/hibernate-orm/blob/5e747b7057902d973f2571619e63ae189c49af46/hibernate-core/src/main/java/org/hibernate/hql/internal/ast/QueryTranslatorImpl.java#L374

here, it must contain collection fetches, but I don't use join fetch, so hb think it doesn't need distinction.
