### ISSUE TITLE
HibernateSpringBootLeftJoinFetch/README.md  error

### ISSUE THREAD

**Issue by totemtec** [AnghelLeonard/Hibernate-SpringBoot#4]
Similar, we can fetch all `Book`, including those with no registered `Author`. This can be done via `JOIN FETCH` or `**JOIN**`.
`JOIN` didn't return all `Book`. The result excluding the record when the author_id is null.

**Comment by AnghelLeonard** [comment]
If you refer to the below two queries:

@Query(value = "SELECT b FROM Book b LEFT JOIN FETCH b.author")
@Query(value = "SELECT b, a FROM Book b LEFT JOIN b.author a")

Then, both of them produces the same SQL, therefore the same result:

SELECT book0_.id AS id1_1_0_,
       author1_.id AS id1_0_1_,
       book0_.author_id AS author_i4_1_0_,
       book0_.isbn AS isbn2_1_0_,
       book0_.title AS title3_1_0_,
       author1_.age AS age2_0_1_,
       author1_.genre AS genre3_0_1_,
       author1_.name AS name4_0_1_
FROM book book0_
LEFT OUTER JOIN author author1_ ON book0_.author_id=author1_.id

And, the output should be:

Book title: A History of Ancient Prague Author: Author{id=4, name=Joana Nimar, genre=History, age=34}
Book title: A People's History Author: Author{id=4, name=Joana Nimar, genre=History, age=34}
Book title: The Beatles Anthology Author: Author{id=1, name=Mark Janel, genre=Anthology, age=23}
Book title: Carrie Author: Author{id=2, name=Olivia Goy, genre=Horror, age=43}
Book title: Master Piece Author: null

If you refer to something else, please be more specific. Thanks!

**Comment by totemtec** [comment]
This can be done via JOIN FETCH or **JOIN**
Should be : 
This can be done via JOIN FETCH or ** LEFT JOIN**

**Comment by AnghelLeonard** [comment]
Ohh! Thanks, good catch! Fixed!
