### ISSUE TITLE
Extra queries on @OneToOne relation with lazy fetch type 

### ISSUE THREAD

**Issue by nicozorza** [AnghelLeonard/Hibernate-SpringBoot#5]
I tried the example with the `hibernate-enhance-maven-plugin` activated, and confirmed that direct @OneToOne relations were being lazily loaded. I created a Book class with a @OneToOne to Author, and every time I fetched a book, the author was being fetched lazily:
```
select book0_.id as id1_1_0_, book0_.author as author2_1_0_ from book book0_ where book0_.id=?
```

However, when I fetch an Author, which has an inverse @OneToOne relation with Book, an extra query is being excecuted:
```
select author0_.id as id1_0_0_, author0_.age as age2_0_0_, author0_.avatar as avatar3_0_0_, author0_.genre as genre4_0_0_, author0_.name as name5_0_0_ from author author0_ where author0_.id=?
select book0_.id as id1_1_0_, book0_.author as author2_1_0_ from book book0_ where book0_.author=?  // <-- This shouldn't be fetched
```
I read that this happens because hibernate does not know if it has to create a proxy or load it with a null reference, but I thought that the enhancement plugin fixed this.

This is the book class I created:
```
@Entity
public class Book implements Serializable {
    private static final long serialVersionUID = 2L;

    @Id
    public Long id;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "author")
    public Author author;
}
```
and the author class is the same as in the example, but I added the inverse relation:
```
@OneToOne(mappedBy = "author", fetch = FetchType.LAZY)
Book book;
```

Is there an error in my tests or it's still a limitation in the library? How are we suposed to solve this problem? Since if I fetch a list of objects with inverse relations, I will be making several extra queries and it will negatively impact on the performance

Forgot to mention: I also tried using @LazyToOne and @LazyGroup annotations in each field, but had the same results.

**Comment by AnghelLeonard** [comment]
Thanks for your comment! I suggest you try @MapsId (https://github.com/AnghelLeonard/Hibernate-SpringBoot/tree/master/HibernateSpringBootOneToOneMapsId). You can find more details in my book, Spring Boot Persistence Best Practices.

**Comment by AnghelLeonard** [comment]
And, the enhancement plugin is useful for lazy loading attributes of the entity not to lazy load relationships. For such cases, as you have, FetcType.LAZY is all you need.
